-- ═══ Comentarios de posts (Instagram + Facebook) para el CRM omnicanal ═══
-- Los comentarios NO son conversaciones 1:1 → tabla propia (many-to-one contra
-- un post). Ingesta por ig-webhook (field 'comments') / fb-webhook (field 'feed');
-- respuesta pública vía la edge function social-comment-reply (POST a
-- {comment-id}/replies en IG o {comment-id}/comments en FB).
--
-- Ruteo del webhook por la cuenta conectada (social_accounts): IG por IGSID del
-- negocio (channel='instagram'), FB por PAGE_ID (channel='messenger').

create table if not exists public.social_comments (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  channel text not null check (channel in ('instagram', 'facebook')),
  external_comment_id text not null,     -- id del comentario en Meta
  parent_comment_id text,                -- id del comentario padre (null = top-level)
  post_id text,                          -- media id (IG) / post_id (FB)
  post_permalink text,
  author_id text,                        -- IGSID / user id del autor
  author_name text,
  author_username text,
  text text,
  media_url text,
  is_mine boolean not null default false, -- true = respuesta nuestra
  status text not null default 'open' check (status in ('open', 'replied', 'hidden')),
  created_at timestamptz not null default now()
);

-- Dedupe de webhooks (Meta puede reintentar) + idempotencia del reply.
create unique index if not exists social_comments_channel_extid_uidx
  on public.social_comments (channel, external_comment_id);
-- Lista del inbox de comentarios: por tenant/canal, más recientes primero.
create index if not exists social_comments_tenant_idx
  on public.social_comments (tenant_id, channel, created_at desc);
-- Agrupar por post.
create index if not exists social_comments_post_idx
  on public.social_comments (tenant_id, post_id);

alter table public.social_comments enable row level security;

-- Miembros del tenant leen; las edge functions escriben con service role.
create policy social_comments_tenant_select on public.social_comments
  for select to authenticated
  using (exists (
    select 1 from users_tenants ut
    join users u on u.id = ut.user_id
    where ut.tenant_id = social_comments.tenant_id
      and u.auth_user_id = auth.uid()
  ));
