-- ═══ Fundación omnicanal de la bandeja de chats (WhatsApp + Instagram + TikTok) ═══
-- Aplicada a prod el 2026-07-22 vía MCP. Diseño: misma bandeja (chats/chat_messages)
-- para todos los canales; WhatsApp mantiene whatsapp_accounts (funciones vivas en
-- prod), las redes nuevas usan social_accounts.

-- 1) Canal por conversación (default whatsapp = backfill implícito de lo existente).
alter table chats add column if not exists channel text not null default 'whatsapp';

-- 2) Identidad del cliente en redes SIN teléfono: IGSID (Instagram) / open_id
--    (TikTok) + username visible. El ruteo de webhooks de IG es por IGSID.
alter table chats add column if not exists external_user_id text;
alter table chats add column if not exists customer_username text;

create index if not exists chats_tenant_channel_idx on chats (tenant_id, channel);
create unique index if not exists chats_channel_external_uidx
  on chats (tenant_id, channel, external_user_id)
  where external_user_id is not null;

-- 3) Cuentas conectadas de redes sociales por tenant (espejo de whatsapp_accounts).
--    Tokens de IG duran 60 días → refresh_token/token_expires_at + cron de refresh.
create table if not exists social_accounts (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  channel text not null check (channel in ('instagram','tiktok','messenger')),
  external_account_id text not null,
  username text,
  display_name text,
  access_token text,
  refresh_token text,
  token_expires_at timestamptz,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists social_accounts_channel_account_uidx
  on social_accounts (channel, external_account_id);
create index if not exists social_accounts_tenant_idx
  on social_accounts (tenant_id, channel);

alter table social_accounts enable row level security;

-- Los tokens NUNCA viajan al navegador: authenticated solo lee columnas
-- "públicas" (privilegios por columna); las edge functions usan service role.
revoke all on social_accounts from anon, authenticated;
grant select (id, tenant_id, channel, external_account_id, username,
              display_name, status, token_expires_at, created_at)
  on social_accounts to authenticated;

create policy social_accounts_tenant_select on social_accounts
  for select to authenticated
  using (exists (
    select 1 from users_tenants ut
    join users u on u.id = ut.user_id
    where ut.tenant_id = social_accounts.tenant_id
      and u.auth_user_id = auth.uid()
  ));
