-- Sequential invoice numbers per calendar year, generated by trigger so
-- the internal admin app does NOT need to know about this column. Format:
-- INV-YYYY-NNNN (e.g. INV-2026-0042). Year resets to 0001 each January.
ALTER TABLE public.tenant_subscriptions
  ADD COLUMN IF NOT EXISTS invoice_number TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS customer_tax_id TEXT,
  ADD COLUMN IF NOT EXISTS customer_address TEXT;

COMMENT ON COLUMN public.tenant_subscriptions.invoice_number IS
  'Auto-generated INV-YYYY-NNNN. Stable identifier exposed to the customer in Mi Perfil > Suscripción.';
COMMENT ON COLUMN public.tenant_subscriptions.customer_tax_id IS
  'Customer fiscal ID (RIF, CI, RUT, etc). NULL until the internal app captures it.';
COMMENT ON COLUMN public.tenant_subscriptions.customer_address IS
  'Customer fiscal address. NULL until the internal app captures it.';

-- The counter pulls from a year-scoped advisory lock so concurrent inserts
-- can't collide. Using lpad(N, 4) gives us up to 9999 invoices/year — more
-- than enough.
CREATE OR REPLACE FUNCTION public.generate_invoice_number()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_year INT := EXTRACT(YEAR FROM COALESCE(NEW.started_at, NOW()));
  v_next_seq INT;
BEGIN
  IF NEW.invoice_number IS NOT NULL THEN
    RETURN NEW;
  END IF;

  -- Advisory lock keyed to the year so two simultaneous inserts in 2026
  -- can't both grab seq=42.
  PERFORM pg_advisory_xact_lock(hashtext('invoice_seq_' || v_year));

  SELECT COALESCE(MAX(
    NULLIF(REGEXP_REPLACE(invoice_number, '^INV-' || v_year || '-', ''), '')::INT
  ), 0) + 1
  INTO v_next_seq
  FROM public.tenant_subscriptions
  WHERE invoice_number LIKE 'INV-' || v_year || '-%';

  NEW.invoice_number := 'INV-' || v_year || '-' || LPAD(v_next_seq::TEXT, 4, '0');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_generate_invoice_number ON public.tenant_subscriptions;
CREATE TRIGGER trg_generate_invoice_number
  BEFORE INSERT ON public.tenant_subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION public.generate_invoice_number();

-- Backfill existing rows. Order by started_at so the numbering reflects
-- the actual chronology of the manual subscriptions, not row insertion
-- order in the table.
DO $$
DECLARE
  r RECORD;
  v_year INT;
  v_year_seq INT;
  v_last_year INT := -1;
BEGIN
  FOR r IN
    SELECT id, started_at
    FROM public.tenant_subscriptions
    WHERE invoice_number IS NULL
    ORDER BY started_at NULLS LAST, id
  LOOP
    v_year := EXTRACT(YEAR FROM COALESCE(r.started_at, NOW()));
    IF v_year <> v_last_year THEN
      v_year_seq := 1;
      v_last_year := v_year;
    ELSE
      v_year_seq := v_year_seq + 1;
    END IF;
    UPDATE public.tenant_subscriptions
       SET invoice_number = 'INV-' || v_year || '-' || LPAD(v_year_seq::TEXT, 4, '0')
     WHERE id = r.id;
  END LOOP;
END $$;
