-- Payments foundation (módulo Pasarelas de Pago, modelo Opción B / OAuth).
--
-- tenant_payment_accounts: la cuenta de pasarela que cada comerciante conecta.
--   - connection_type 'oauth'  → tokens obtenidos por OAuth (ej. Mercado Pago).
--   - connection_type 'api_keys' → el comerciante pega sus llaves (Wompi, Culqi,
--     Flow, Stripe).
--   access_token / refresh_token son secretos: la RLS los limita a los miembros
--   del propio tenant (son las credenciales del propio comerciante); las edge
--   functions los leen con service_role para cobrar. El catálogo público (anon)
--   no tiene membresía → no puede leerlos.

CREATE TABLE IF NOT EXISTS public.tenant_payment_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  connection_type TEXT NOT NULL DEFAULT 'api_keys',
  public_key TEXT,
  access_token TEXT,
  refresh_token TEXT,
  webhook_secret TEXT,
  external_account_id TEXT,
  country_code TEXT,
  status TEXT NOT NULL DEFAULT 'connected',
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  token_expires_at TIMESTAMPTZ,
  connected_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT tenant_payment_accounts_provider_chk
    CHECK (provider IN ('mercadopago', 'stripe', 'wompi', 'culqi', 'flow')),
  CONSTRAINT tenant_payment_accounts_conn_chk
    CHECK (connection_type IN ('oauth', 'api_keys')),
  CONSTRAINT tenant_payment_accounts_status_chk
    CHECK (status IN ('connected', 'revoked')),
  CONSTRAINT tenant_payment_accounts_unique UNIQUE (tenant_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_tenant_payment_accounts_tenant
  ON public.tenant_payment_accounts (tenant_id);

-- Estado de pago por orden.
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS payment_provider TEXT,
  ADD COLUMN IF NOT EXISTS payment_id TEXT,
  ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;

-- RLS: solo los miembros del tenant gestionan sus propias cuentas de pago.
ALTER TABLE public.tenant_payment_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_payment_accounts_member_all
  ON public.tenant_payment_accounts FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.users_tenants ut
    JOIN public.users u ON u.id = ut.user_id
    WHERE ut.tenant_id = tenant_payment_accounts.tenant_id
      AND u.auth_user_id = auth.uid()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.users_tenants ut
    JOIN public.users u ON u.id = ut.user_id
    WHERE ut.tenant_id = tenant_payment_accounts.tenant_id
      AND u.auth_user_id = auth.uid()
  ));
